### PR TITLE
Use git2 instead of spawning git

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by quadrupleslap** [comment]
Thanks! That's a great idea, but should we just remove the failing Appveyor and Travis builds? I'm not sure anyone even uses `i686-apple-darwin` anymore.

**Comment by lnicola** [comment]
Oops, sorry, I hadn't noticed the CI.

I'd rather not break the Windows builds with this PR, but I'm not sure what to make of the build log.

**Comment by lnicola** [comment]
Is it saying it can't find `make`?

**Comment by quadrupleslap** [comment]
The MSYS Windows builds still work, but it looks like CMake is still assuming it's building with MSYS on the MinGW builds.

**Comment by lnicola** [comment]
MinGW works now, but I removed `i686-apple-darwin` from Travis.

**Comment by quadrupleslap** [comment]
That's fine! :)

**Pull request merged**
